//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBriscola.Strings.es {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CBriscola.Strings.es.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a por.
        /// </summary>
        internal static string AdOperaDi {
            get {
                return ResourceManager.GetString("AdOperaDi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Alice Victoria.
        /// </summary>
        internal static string Autore {
            get {
                return ResourceManager.GetString("Autore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a bastos.
        /// </summary>
        internal static string bastoni {
            get {
                return ResourceManager.GetString("bastoni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Il seme de brisca es.
        /// </summary>
        internal static string CartaBriscola {
            get {
                return ResourceManager.GetString("CartaBriscola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Por favor, inserte el número de la tarjeta que desea jugar.
        /// </summary>
        internal static string CartaDaGiocare {
            get {
                return ResourceManager.GetString("CartaDaGiocare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a cartas.
        /// </summary>
        internal static string carte {
            get {
                return ResourceManager.GetString("carte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a En la baraja sobra.
        /// </summary>
        internal static string CarteMazzo {
            get {
                return ResourceManager.GetString("CarteMazzo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a copas.
        /// </summary>
        internal static string coppe {
            get {
                return ResourceManager.GetString("coppe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a oro.
        /// </summary>
        internal static string denari {
            get {
                return ResourceManager.GetString("denari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a desde.
        /// </summary>
        internal static string di {
            get {
                return ResourceManager.GetString("di", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Carta jugada.
        /// </summary>
        internal static string Giocata {
            get {
                return ResourceManager.GetString("Giocata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tienes perdido por.
        /// </summary>
        internal static string HaiPersoPer {
            get {
                return ResourceManager.GetString("HaiPersoPer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tienes ganado po.
        /// </summary>
        internal static string HaiVintoPer {
            get {
                return ResourceManager.GetString("HaiVintoPer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Valor no válido. Por favor inserte un número entre 1 y.
        /// </summary>
        internal static string InserisciNuovoNumero {
            get {
                return ResourceManager.GetString("InserisciNuovoNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a La jugada es en paridad.
        /// </summary>
        internal static string ParitaPatta {
            get {
                return ResourceManager.GetString("ParitaPatta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a La jugada se acabo..
        /// </summary>
        internal static string PartitaFinita {
            get {
                return ResourceManager.GetString("PartitaFinita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Presiona regresar para salir.
        /// </summary>
        internal static string PremereInvio {
            get {
                return ResourceManager.GetString("PremereInvio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a puntos.
        /// </summary>
        internal static string punti {
            get {
                return ResourceManager.GetString("punti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Puntos de Cpu.
        /// </summary>
        internal static string PuntiCpu {
            get {
                return ResourceManager.GetString("PuntiCpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tus puntos.
        /// </summary>
        internal static string PuntiUtente {
            get {
                return ResourceManager.GetString("PuntiUtente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a espadas.
        /// </summary>
        internal static string spade {
            get {
                return ResourceManager.GetString("spade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Traducción.
        /// </summary>
        internal static string Traduzione {
            get {
                return ResourceManager.GetString("Traduzione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a valor no válido.
        /// </summary>
        internal static string ValoreNonValido {
            get {
                return ResourceManager.GetString("ValoreNonValido", resourceCulture);
            }
        }
    }
}
